// Mirrors com.recruitsystem.entity.auth.UserRole on the backend.
export const ROLES = {
  JOB_SEEKER: 'JOB_SEEKER',
  RECRUITER: 'RECRUITER',
  HR_EXECUTIVE: 'HR_EXECUTIVE',
  INTERVIEW_PANEL_MEMBER: 'INTERVIEW_PANEL_MEMBER',
  SYSTEM_ADMINISTRATOR: 'SYSTEM_ADMINISTRATOR',
}

export const CANDIDATE_ROLES = [ROLES.JOB_SEEKER]
export const RECRUITER_HR_ROLES = [ROLES.RECRUITER, ROLES.HR_EXECUTIVE, ROLES.INTERVIEW_PANEL_MEMBER]
export const ADMIN_ROLES = [ROLES.SYSTEM_ADMINISTRATOR]
